prompt_folder = "."
prompts = "agentprompts"
input_folder = "jobDescriptions"
database_name = "taxonomy.db"
sqlite_datapath = "sqliteData"
rag_datapath = "chromadb"
rag_embed_llm = "nomic-embed-text"
rag_embed_url = "http://localhost:11434/api/embeddings"
rag_distance = 0.2
rag_distmatch = 0.3
rag_cluster = 0.3
rag_scenario = 0.35
rag_same = 0.07
rag_hnsw_space = "cosine"
main_llm_name = "llama3.1:latest"
llm_base_url = "http://localhost:11434/v1"
